import { ICategoryElement } from 'app/shared/model/category-element.model';
import { ICustom } from 'app/shared/model/custom.model';
import { ITransportationType } from 'app/shared/model/transportation-type.model';
import { ITradeTypeCode } from 'app/shared/model/trade-type-code.model';
import { IPaymentCondition } from 'app/shared/model/payment-condition.model';
import { IJustificationDeductionAmount } from 'app/shared/model/justification-deduction-amount.model';
import { IProduct } from 'app/shared/model/product.model';
import { IDocumentTransaction } from 'app/shared/model/document-transaction.model';

export interface ICustomJustification {
  id?: number;
  agentId?: number | null;
  agriculturalPublicPolicies?: string | null;
  assessmentPlace?: string | null;
  attachedDocuments?: string | null;
  balanceRate?: number | null;
  bankCode?: string | null;
  borderTransportType?: string | null;
  boxCountType?: string | null;
  boxMarks?: string | null;
  cargoIndexNumber?: string | null;
  centralBankCreditCode?: string | null;
  comments?: string | null;
  constructorCountryCode?: string | null;
  costDetails?: string | null;
  cottageNumber?: number | null;
  creditEquivalentAmount?: number | null;
  currency?: string | null;
  currencyAmount?: number | null;
  currencyRate?: number | null;
  currencySwiftCode?: string | null;
  customCompanyCode?: string | null;
  customerId?: number | null;
  date?: string | null;
  destCountryCode?: string | null;
  destCustom?: string | null;
  destCustomCode?: string | null;
  disciplinaryDocumentsIssued?: boolean | null;
  discountPercent?: number | null;
  eightDigitOrderCode?: string | null;
  entranceCustomCompany?: number | null;
  entranceCustomCompanyId?: number | null;
  evacuationPlace?: string | null;
  evaluationMethodCode?: string | null;
  exportDate?: string | null;
  exporter?: string | null;
  exporterCountryCode?: string | null;
  extensionDate?: string | null;
  factorTotalAmount?: string | null;
  freightIndexNumber?: string | null;
  frightLetter?: string | null;
  importLicence?: string | null;
  importLicense?: string | null;
  impureWeight?: number | null;
  indices?: string | null;
  internalTransportType?: string | null;
  issuanceDate?: string | null;
  itemNumber?: string | null;
  items?: number | null;
  justificationAgent?: string | null;
  justificationCurrencyRate?: number | null;
  licenceNumber?: string | null;
  makeCertificateNumber?: string | null;
  newBorderTransportType?: number | null;
  newEvacuationPlace?: number | null;
  newInternalTransportType?: number | null;
  newProductItemCustomValue?: number | null;
  orderRegistrationDate?: string | null;
  orderRegistrationNumber?: string | null;
  papers?: number | null;
  paymentConditions?: string | null;
  preferences?: string | null;
  procedure?: string | null;
  productBoxCount?: number | null;
  productCode?: string | null;
  productItemCost?: number | null;
  productItemCount?: string | null;
  productItemCustomValue?: string | null;
  productItemValue?: string | null;
  productMeasure?: string | null;
  productOwner?: string | null;
  productReleaseDate?: string | null;
  productType?: string | null;
  productWorth?: number | null;
  profitRate?: number | null;
  pureWeight?: number | null;
  quota?: string | null;
  receiver?: string | null;
  referenceNumber?: number | null;
  registrationNumber?: string | null;
  reverseOfJustificationDisciplinaryDocumentNumber?: string | null;
  reverseOfJustificationDocumentsIssued?: boolean | null;
  rightsRate?: number | null;
  tradingCountryCode?: string | null;
  transactionTypeCode?: string | null;
  warehouseFactorNumber?: string | null;
  constructorCountryName?: string | null;
  lastCountryName?: string | null;
  branchCode?: string | null;
  justificationCurrencyCode?: string | null;
  creditCurrencyCode?: string | null;
  isMigrational?: boolean | null;
  originalLetterImageContentType?: string | null;
  originalLetterImage?: string | null;
  letterImageContentType?: string | null;
  letterImage?: string | null;
  sourceCountryCode?: string | null;
  vehicleEnterNationality?: ICategoryElement | null;
  container?: ICategoryElement | null;
  vehicleCrossNationality?: ICategoryElement | null;
  exportCustom?: ICustom | null;
  entranceCustom?: ICustom | null;
  transportConditions?: ITransportationType | null;
  tradeTypeCode?: ITradeTypeCode | null;
  newPaymentConditions?: IPaymentCondition | null;
  justificationDeductionAmount?: IJustificationDeductionAmount | null;
  products?: IProduct[] | null;
  reverseOfJustificationDocumentTransactions?: IDocumentTransaction[] | null;
}

export const defaultValue: Readonly<ICustomJustification> = {
  disciplinaryDocumentsIssued: false,
  reverseOfJustificationDocumentsIssued: false,
  isMigrational: false,
};
