package com.dotin.tfbita.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AdvisorDefinitionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdvisorDefinitionAllPropertiesEquals(AdvisorDefinition expected, AdvisorDefinition actual) {
        assertAdvisorDefinitionAutoGeneratedPropertiesEquals(expected, actual);
        assertAdvisorDefinitionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdvisorDefinitionAllUpdatablePropertiesEquals(AdvisorDefinition expected, AdvisorDefinition actual) {
        assertAdvisorDefinitionUpdatableFieldsEquals(expected, actual);
        assertAdvisorDefinitionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdvisorDefinitionAutoGeneratedPropertiesEquals(AdvisorDefinition expected, AdvisorDefinition actual) {
        assertThat(expected)
            .as("Verify AdvisorDefinition auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdvisorDefinitionUpdatableFieldsEquals(AdvisorDefinition expected, AdvisorDefinition actual) {
        assertThat(expected)
            .as("Verify AdvisorDefinition relevant properties")
            .satisfies(e -> assertThat(e.getCaption()).as("check caption").isEqualTo(actual.getCaption()))
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getCountryIsoCode()).as("check countryIsoCode").isEqualTo(actual.getCountryIsoCode()))
            .satisfies(e -> assertThat(e.getDepositNum()).as("check depositNum").isEqualTo(actual.getDepositNum()))
            .satisfies(e -> assertThat(e.getSwiftCode()).as("check swiftCode").isEqualTo(actual.getSwiftCode()))
            .satisfies(
                e -> assertThat(e.getDefaultCurrencyCode()).as("check defaultCurrencyCode").isEqualTo(actual.getDefaultCurrencyCode())
            )
            .satisfies(e -> assertThat(e.getCurrenciesCodes()).as("check currenciesCodes").isEqualTo(actual.getCurrenciesCodes()))
            .satisfies(e -> assertThat(e.getCountryCode()).as("check countryCode").isEqualTo(actual.getCountryCode()))
            .satisfies(e -> assertThat(e.getBankCode()).as("check bankCode").isEqualTo(actual.getBankCode()))
            .satisfies(e -> assertThat(e.getBranchCode()).as("check branchCode").isEqualTo(actual.getBranchCode()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdvisorDefinitionUpdatableRelationshipsEquals(AdvisorDefinition expected, AdvisorDefinition actual) {
        assertThat(expected)
            .as("Verify AdvisorDefinition relationships")
            .satisfies(
                e ->
                    assertThat(e.getAdditionalBrokerInformation())
                        .as("check additionalBrokerInformation")
                        .isEqualTo(actual.getAdditionalBrokerInformation())
            )
            .satisfies(
                e -> assertThat(e.getDefaultVostroDeposit()).as("check defaultVostroDeposit").isEqualTo(actual.getDefaultVostroDeposit())
            )
            .satisfies(
                e -> assertThat(e.getDefaultNostroDeposit()).as("check defaultNostroDeposit").isEqualTo(actual.getDefaultNostroDeposit())
            )
            .satisfies(e -> assertThat(e.getReceiveMethod()).as("check receiveMethod").isEqualTo(actual.getReceiveMethod()))
            .satisfies(e -> assertThat(e.getPayMethod()).as("check payMethod").isEqualTo(actual.getPayMethod()))
            .satisfies(e -> assertThat(e.getSwiftBic()).as("check swiftBic").isEqualTo(actual.getSwiftBic()));
    }
}
