package com.dotin.tfbita.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DraftRequestTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDraftRequestTypeAllPropertiesEquals(DraftRequestType expected, DraftRequestType actual) {
        assertDraftRequestTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertDraftRequestTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDraftRequestTypeAllUpdatablePropertiesEquals(DraftRequestType expected, DraftRequestType actual) {
        assertDraftRequestTypeUpdatableFieldsEquals(expected, actual);
        assertDraftRequestTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDraftRequestTypeAutoGeneratedPropertiesEquals(DraftRequestType expected, DraftRequestType actual) {
        assertThat(expected)
            .as("Verify DraftRequestType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDraftRequestTypeUpdatableFieldsEquals(DraftRequestType expected, DraftRequestType actual) {}

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDraftRequestTypeUpdatableRelationshipsEquals(DraftRequestType expected, DraftRequestType actual) {}
}
