package com.dotin.tfbita.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PaymentItemTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentItemTypeAllPropertiesEquals(PaymentItemType expected, PaymentItemType actual) {
        assertPaymentItemTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertPaymentItemTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentItemTypeAllUpdatablePropertiesEquals(PaymentItemType expected, PaymentItemType actual) {
        assertPaymentItemTypeUpdatableFieldsEquals(expected, actual);
        assertPaymentItemTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentItemTypeAutoGeneratedPropertiesEquals(PaymentItemType expected, PaymentItemType actual) {
        assertThat(expected)
            .as("Verify PaymentItemType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentItemTypeUpdatableFieldsEquals(PaymentItemType expected, PaymentItemType actual) {
        assertThat(expected)
            .as("Verify PaymentItemType relevant properties")
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentItemTypeUpdatableRelationshipsEquals(PaymentItemType expected, PaymentItemType actual) {}
}
