package com.dotin.tfbita.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TradeTypeCodeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTradeTypeCodeAllPropertiesEquals(TradeTypeCode expected, TradeTypeCode actual) {
        assertTradeTypeCodeAutoGeneratedPropertiesEquals(expected, actual);
        assertTradeTypeCodeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTradeTypeCodeAllUpdatablePropertiesEquals(TradeTypeCode expected, TradeTypeCode actual) {
        assertTradeTypeCodeUpdatableFieldsEquals(expected, actual);
        assertTradeTypeCodeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTradeTypeCodeAutoGeneratedPropertiesEquals(TradeTypeCode expected, TradeTypeCode actual) {
        assertThat(expected)
            .as("Verify TradeTypeCode auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTradeTypeCodeUpdatableFieldsEquals(TradeTypeCode expected, TradeTypeCode actual) {
        assertThat(expected)
            .as("Verify TradeTypeCode relevant properties")
            .satisfies(e -> assertThat(e.getLatinName()).as("check latinName").isEqualTo(actual.getLatinName()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTradeTypeCodeUpdatableRelationshipsEquals(TradeTypeCode expected, TradeTypeCode actual) {}
}
