package com.dotin.tfbita.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TransportationTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransportationTypeAllPropertiesEquals(TransportationType expected, TransportationType actual) {
        assertTransportationTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertTransportationTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransportationTypeAllUpdatablePropertiesEquals(TransportationType expected, TransportationType actual) {
        assertTransportationTypeUpdatableFieldsEquals(expected, actual);
        assertTransportationTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransportationTypeAutoGeneratedPropertiesEquals(TransportationType expected, TransportationType actual) {
        assertThat(expected)
            .as("Verify TransportationType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransportationTypeUpdatableFieldsEquals(TransportationType expected, TransportationType actual) {
        assertThat(expected)
            .as("Verify TransportationType relevant properties")
            .satisfies(e -> assertThat(e.getLatinName()).as("check latinName").isEqualTo(actual.getLatinName()))
            .satisfies(e -> assertThat(e.getModificationDate()).as("check modificationDate").isEqualTo(actual.getModificationDate()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransportationTypeUpdatableRelationshipsEquals(TransportationType expected, TransportationType actual) {}
}
