package com.dotin.tfbita.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TransferMethodManagementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransferMethodManagementAllPropertiesEquals(
        TransferMethodManagement expected,
        TransferMethodManagement actual
    ) {
        assertTransferMethodManagementAutoGeneratedPropertiesEquals(expected, actual);
        assertTransferMethodManagementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransferMethodManagementAllUpdatablePropertiesEquals(
        TransferMethodManagement expected,
        TransferMethodManagement actual
    ) {
        assertTransferMethodManagementUpdatableFieldsEquals(expected, actual);
        assertTransferMethodManagementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransferMethodManagementAutoGeneratedPropertiesEquals(
        TransferMethodManagement expected,
        TransferMethodManagement actual
    ) {
        assertThat(expected)
            .as("Verify TransferMethodManagement auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransferMethodManagementUpdatableFieldsEquals(
        TransferMethodManagement expected,
        TransferMethodManagement actual
    ) {
        assertThat(expected)
            .as("Verify TransferMethodManagement relevant properties")
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getDesc()).as("check desc").isEqualTo(actual.getDesc()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransferMethodManagementUpdatableRelationshipsEquals(
        TransferMethodManagement expected,
        TransferMethodManagement actual
    ) {
        assertThat(expected)
            .as("Verify TransferMethodManagement relationships")
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()));
    }
}
